# Generated by Django 4.1.7 on 2023-03-15 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kortTittel', models.CharField(max_length=3)),
                ('langTittel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medlem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(default='Ola Nordmann', max_length=100)),
                ('fødselsdato', models.DateField(blank=True, null=True)),
                ('epost', models.EmailField(blank=True, max_length=100)),
                ('tlf', models.BigIntegerField(blank=True, null=True)),
                ('studieEllerJobb', models.CharField(blank=True, max_length=100)),
                ('boAdresse', models.CharField(blank=True, max_length=100)),
                ('foreldreAdresse', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medlem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tilgang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Verv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=30)),
                ('kor', models.ManyToManyField(related_name='verv', to='mytxs.kor')),
                ('tilganger', models.ManyToManyField(related_name='verv', to='mytxs.tilgang')),
            ],
        ),
        migrations.CreateModel(
            name='VervInnehavelse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('slutt', models.DateField()),
                ('medlem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vervInnehavelse', to='mytxs.medlem')),
                ('verv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vervInnehavelse', to='mytxs.verv')),
            ],
        ),
    ]
