# Generated by Django 4.2 on 2023-06-04 08:39

from django.db import migrations, models
import django.db.models.deletion
import mytxs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dekorasjon',
            options={'ordering': ['kor', 'navn'], 'verbose_name_plural': 'dekorasjoner'},
        ),
        migrations.AlterModelOptions(
            name='dekorasjoninnehavelse',
            options={'ordering': ['start'], 'verbose_name_plural': 'dekorasjoninnehavelser'},
        ),
        migrations.AlterModelOptions(
            name='kor',
            options={'verbose_name_plural': 'kor'},
        ),
        migrations.AlterModelOptions(
            name='medlem',
            options={'verbose_name_plural': 'medlemmer'},
        ),
        migrations.AlterModelOptions(
            name='tilgang',
            options={'ordering': ['kor', 'navn'], 'verbose_name_plural': 'tilganger'},
        ),
        migrations.AlterModelOptions(
            name='verv',
            options={'ordering': ['kor', models.Case(models.When(navn='1S', then=0), models.When(navn='11S', then=1), models.When(navn='21S', then=2), models.When(navn='2S', then=3), models.When(navn='12S', then=4), models.When(navn='22S', then=5), models.When(navn='1A', then=6), models.When(navn='11A', then=7), models.When(navn='21A', then=8), models.When(navn='2A', then=9), models.When(navn='12A', then=10), models.When(navn='22A', then=11), models.When(navn='1T', then=12), models.When(navn='11T', then=13), models.When(navn='21T', then=14), models.When(navn='2T', then=15), models.When(navn='12T', then=16), models.When(navn='22T', then=17), models.When(navn='1B', then=18), models.When(navn='11B', then=19), models.When(navn='21B', then=20), models.When(navn='2B', then=21), models.When(navn='12B', then=22), models.When(navn='22B', then=23), default=24), 'navn'], 'verbose_name_plural': 'verv'},
        ),
        migrations.AlterModelOptions(
            name='vervinnehavelse',
            options={'ordering': ['start'], 'verbose_name_plural': 'vervinnehavelser'},
        ),
        migrations.AddField(
            model_name='tilgang',
            name='beskrivelse',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tilgang',
            name='brukt',
            field=models.BooleanField(default=False, help_text='<span title="Hvorvidt tilgangen er brukt i kode og følgelig ikke kan endres på av brukere.">(?)</span>'),
        ),
        migrations.AddField(
            model_name='tilgang',
            name='kor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tilganger', to='mytxs.kor'),
        ),
        migrations.AlterField(
            model_name='kor',
            name='kortTittel',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tilgang',
            name='navn',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='verv',
            name='navn',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='verv',
            name='tilganger',
            field=mytxs.fields.MyManyToManyField(blank=True, related_name='verv', to='mytxs.tilgang'),
        ),
        migrations.AlterUniqueTogether(
            name='tilgang',
            unique_together={('kor', 'navn')},
        ),
        migrations.CreateModel(
            name='LoggM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=50)),
                ('fromPK', models.PositiveIntegerField()),
                ('toPK', models.PositiveIntegerField()),
                ('change', models.SmallIntegerField(choices=[(1, 'Create'), (-1, 'Delete')])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m2mlogger', to='mytxs.medlem')),
            ],
            options={
                'ordering': ['-timeStamp'],
            },
        ),
        migrations.CreateModel(
            name='Logg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('change', models.SmallIntegerField(choices=[(1, 'Create'), (0, 'Update'), (-1, 'Delete')])),
                ('model', models.CharField(max_length=50)),
                ('instancePK', models.PositiveIntegerField()),
                ('value', models.JSONField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logger', to='mytxs.medlem')),
                ('kor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logger', to='mytxs.kor')),
            ],
            options={
                'verbose_name_plural': 'logger',
                'ordering': ['-timeStamp'],
            },
        ),
    ]
