# Generated by Django 4.1.7 on 2023-03-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilgang',
            name='navn',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
