# Generated by Django 4.2 on 2023-06-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0002_alter_dekorasjon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medlem',
            options={'ordering': ['fornavn', 'mellomnavn', 'etternavn'], 'verbose_name_plural': 'medlemmer'},
        ),
        migrations.AlterField(
            model_name='medlem',
            name='tlf',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
