# Generated by Django 4.1.7 on 2023-03-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0002_alter_tilgang_navn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verv',
            name='kor',
        ),
        migrations.AddField(
            model_name='verv',
            name='kor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verv', to='mytxs.kor'),
        ),
    ]
