# Generated by Django 4.1.7 on 2023-03-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0003_remove_verv_kor_verv_kor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vervinnehavelse',
            name='medlem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vervInnehavelse', to='mytxs.medlem'),
        ),
        migrations.AlterField(
            model_name='vervinnehavelse',
            name='verv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vervInnehavelse', to='mytxs.verv'),
        ),
    ]
