# Generated by Django 4.2 on 2023-06-13 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0003_alter_medlem_options_alter_medlem_tlf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dekorasjoninnehavelse',
            options={'ordering': ['-start'], 'verbose_name_plural': 'dekorasjoninnehavelser'},
        ),
        migrations.AlterModelOptions(
            name='vervinnehavelse',
            options={'ordering': ['-start'], 'verbose_name_plural': 'vervinnehavelser'},
        ),
        migrations.RemoveField(
            model_name='loggm2m',
            name='author',
        ),
        migrations.RemoveField(
            model_name='loggm2m',
            name='fromPK',
        ),
        migrations.RemoveField(
            model_name='loggm2m',
            name='model',
        ),
        migrations.RemoveField(
            model_name='loggm2m',
            name='toPK',
        ),
        migrations.AddField(
            model_name='logg',
            name='strRep',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loggm2m',
            name='fromLogg',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='forwardM2Ms', to='mytxs.logg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loggm2m',
            name='m2mName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loggm2m',
            name='toLogg',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='backwardM2Ms', to='mytxs.logg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tilgang',
            name='sjekkheftetSynlig',
            field=models.BooleanField(default=False, help_text='<span title="Om de som har denne tilgangen skal vises som en gruppe i sjekkheftet.">(?)</span>'),
        ),
    ]
