# Generated by Django 4.1.7 on 2023-03-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0004_alter_vervinnehavelse_medlem_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verv',
            unique_together={('navn', 'kor')},
        ),
    ]
