# Generated by Django 4.1.7 on 2023-03-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0005_alter_verv_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dekorasjon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=30)),
                ('kor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dekorasjoner', to='mytxs.kor')),
            ],
            options={
                'unique_together': {('navn', 'kor')},
            },
        ),
        migrations.AlterField(
            model_name='verv',
            name='tilganger',
            field=models.ManyToManyField(blank=True, related_name='verv', to='mytxs.tilgang'),
        ),
        migrations.CreateModel(
            name='DekorasjonInnehavelse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('dekorasjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dekorasjonInnehavelse', to='mytxs.dekorasjon')),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dekorasjonInnehavelse', to='mytxs.medlem')),
            ],
        ),
    ]
