# Generated by Django 4.2 on 2023-07-26 15:52

from django.db import migrations, models
import django.db.models.deletion
import mytxs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0005_hendelse_rename_brukt_tilgang_bruktikode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oppmøte',
            options={'ordering': ['-hendelse', 'medlem']},
        ),
        migrations.AlterModelOptions(
            name='verv',
            options={'ordering': ['kor', models.Case(models.When(navn='1S', then=0), models.When(navn='11S', then=1), models.When(navn='21S', then=2), models.When(navn='2S', then=3), models.When(navn='12S', then=4), models.When(navn='22S', then=5), models.When(navn='1A', then=6), models.When(navn='11A', then=7), models.When(navn='21A', then=8), models.When(navn='2A', then=9), models.When(navn='12A', then=10), models.When(navn='22A', then=11), models.When(navn='1T', then=12), models.When(navn='11T', then=13), models.When(navn='21T', then=14), models.When(navn='2T', then=15), models.When(navn='12T', then=16), models.When(navn='22T', then=17), models.When(navn='1B', then=18), models.When(navn='11B', then=19), models.When(navn='21B', then=20), models.When(navn='2B', then=21), models.When(navn='12B', then=22), models.When(navn='22B', then=23), models.When(navn='ukjentStemmegruppe', then=24), default=25), 'navn'], 'verbose_name_plural': 'verv'},
        ),
        migrations.RemoveField(
            model_name='verv',
            name='tilganger',
        ),
        migrations.AddField(
            model_name='dekorasjon',
            name='strRep',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='dekorasjoninnehavelse',
            name='strRep',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='hendelse',
            name='strRep',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='kor',
            name='strRep',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='lenke',
            name='strRep',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='medlem',
            name='død',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medlem',
            name='gammeltMedlemsnummer',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='medlem',
            name='notis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medlem',
            name='strRep',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='medlem',
            name='ønskerVårbrev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oppmøte',
            name='strRep',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='tilgang',
            name='strRep',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='tilgang',
            name='verv',
            field=mytxs.fields.MyManyToManyField(blank=True, related_name='tilganger', to='mytxs.verv'),
        ),
        migrations.AddField(
            model_name='verv',
            name='strRep',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='vervinnehavelse',
            name='strRep',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.CreateModel(
            name='Turne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strRep', models.CharField(default='', editable=False, max_length=200)),
                ('navn', models.CharField(max_length=30)),
                ('start', mytxs.fields.MyDateField()),
                ('slutt', mytxs.fields.MyDateField(blank=True, null=True)),
                ('kor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='turneer', to='mytxs.kor')),
                ('medlemmer', mytxs.fields.MyManyToManyField(blank=True, related_name='turneer', to='mytxs.medlem')),
            ],
            options={
                'verbose_name_plural': 'turneer',
                'ordering': ['kor', '-start', 'navn'],
                'unique_together': {('kor', 'navn', 'start')},
            },
        ),
    ]
