# Generated by Django 4.1.7 on 2023-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0006_dekorasjon_alter_verv_tilganger_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dekorasjon',
            options={'ordering': ['kor', 'navn']},
        ),
        migrations.AlterModelOptions(
            name='dekorasjoninnehavelse',
            options={'ordering': ['start']},
        ),
        migrations.AlterModelOptions(
            name='verv',
            options={'ordering': ['kor', 'navn']},
        ),
        migrations.AlterModelOptions(
            name='vervinnehavelse',
            options={'ordering': ['start']},
        ),
        migrations.AddField(
            model_name='medlem',
            name='etternavn',
            field=models.CharField(default='Nordmann', max_length=50),
        ),
        migrations.AddField(
            model_name='medlem',
            name='fornavn',
            field=models.CharField(default='Ola', max_length=50),
        ),
        migrations.AddField(
            model_name='medlem',
            name='mellomnavn',
            field=models.CharField(default='', max_length=50),
        ),
    ]
