# Generated by Django 4.1.7 on 2023-04-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0007_alter_dekorasjon_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medlem',
            name='navn',
        ),
    ]
