# Generated by Django 4.2 on 2023-11-16 16:50

from django.db import migrations, models
import mytxs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0007_alter_dekorasjoninnehavelse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medlem',
            name='overførtData',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='hendelse',
            name='sluttDate',
            field=mytxs.fields.MyDateField(blank=True, null=True, verbose_name='Slutt dato'),
        ),
        migrations.AlterField(
            model_name='hendelse',
            name='sluttTime',
            field=mytxs.fields.MyTimeField(blank=True, null=True, verbose_name='Slutt tid'),
        ),
        migrations.AlterField(
            model_name='hendelse',
            name='startDate',
            field=mytxs.fields.MyDateField(help_text='<span title="Oppmøtene for hendelsen, altså for fraværsføring og fraværsmelding, genereres av hvilke medlemmer som er aktive i koret på denne datoen, og ikke har permisjon">(?)</span>', verbose_name='Start dato'),
        ),
        migrations.AlterField(
            model_name='hendelse',
            name='startTime',
            field=mytxs.fields.MyTimeField(blank=True, null=True, verbose_name='Start tid'),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='boAdresse',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bo adresse'),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='foreldreAdresse',
            field=models.CharField(blank=True, max_length=100, verbose_name='Foreldre adresse'),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='gammeltMedlemsnummer',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='Gammelt medlemsnummer'),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='sjekkhefteSynlig',
            field=mytxs.fields.BitmapMultipleChoiceField(blank=True, choicesList=['fødselsdato', 'epost', 'tlf', 'studieEllerJobb', 'boAdresse', 'foreldreAdresse'], default=0, verbose_name='Synlig i sjekkheftet'),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='studieEllerJobb',
            field=models.CharField(blank=True, max_length=100, verbose_name='Studie eller jobb'),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='ønskerVårbrev',
            field=models.BooleanField(default=False, verbose_name='Ønsker vårbrev'),
        ),
        migrations.AlterField(
            model_name='tilgang',
            name='bruktIKode',
            field=models.BooleanField(default=False, help_text='<span title="Hvorvidt tilgangen er brukt i kode og følgelig ikke kan endres på av brukere.">(?)</span>', verbose_name='Brukt i kode'),
        ),
        migrations.AlterField(
            model_name='tilgang',
            name='sjekkheftetSynlig',
            field=models.BooleanField(default=False, help_text='<span title="Om de som har denne tilgangen skal vises som en gruppe i sjekkheftet.">(?)</span>', verbose_name='Synlig i sjekkheftet'),
        ),
        migrations.AlterField(
            model_name='verv',
            name='bruktIKode',
            field=models.BooleanField(default=False, help_text='<span title="Hvorvidt vervet er brukt i kode og følgelig ikke kan endres på av brukere.">(?)</span>', verbose_name='Brukt i kode'),
        ),
    ]
