# Generated by Django 4.2 on 2024-01-08 00:06

from django.db import migrations, models
import django.db.models.deletion
import mytxs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0008_medlem_overførtdata_alter_hendelse_sluttdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kor',
            old_name='kortTittel',
            new_name='navn',
        ),
        migrations.RenameField(
            model_name='kor',
            old_name='langTittel',
            new_name='tittel',
        ),
        migrations.RemoveField(
            model_name='dekorasjon',
            name='strRep',
        ),
        migrations.RemoveField(
            model_name='dekorasjoninnehavelse',
            name='strRep',
        ),
        migrations.RemoveField(
            model_name='hendelse',
            name='strRep',
        ),
        migrations.RemoveField(
            model_name='lenke',
            name='strRep',
        ),
        migrations.RemoveField(
            model_name='medlem',
            name='strRep',
        ),
        migrations.RemoveField(
            model_name='oppmøte',
            name='strRep',
        ),
        migrations.RemoveField(
            model_name='tilgang',
            name='strRep',
        ),
        migrations.RemoveField(
            model_name='turne',
            name='strRep',
        ),
        migrations.RemoveField(
            model_name='verv',
            name='strRep',
        ),
        migrations.RemoveField(
            model_name='vervinnehavelse',
            name='strRep',
        ),
        migrations.AddField(
            model_name='dekorasjon',
            name='dbCacheField',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='dekorasjoninnehavelse',
            name='dbCacheField',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='hendelse',
            name='dbCacheField',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='lenke',
            name='dbCacheField',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='medlem',
            name='dbCacheField',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='medlem',
            name='matpreferanse',
            field=mytxs.fields.BitmapMultipleChoiceField(blank=True, choicesList=['Vegetar', 'Vegan', 'Pescetar', 'Glutenfritt', 'Laktoseintoleranse', 'Nøtteallergi', 'Eggallergi', 'Fiskeallergi', 'Løkallergi', 'Steinfruktallergi'], default=0),
        ),
        migrations.AddField(
            model_name='oppmøte',
            name='dbCacheField',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='tilgang',
            name='dbCacheField',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='turne',
            name='dbCacheField',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='verv',
            name='dbCacheField',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='vervinnehavelse',
            name='dbCacheField',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='dekorasjoninnehavelse',
            name='dekorasjon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dekorasjonInnehavelser', to='mytxs.dekorasjon'),
        ),
        migrations.AlterField(
            model_name='dekorasjoninnehavelse',
            name='medlem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dekorasjonInnehavelser', to='mytxs.medlem'),
        ),
    ]
