# Generated by Django 4.1.7 on 2023-04-13 11:41

from django.db import migrations, models
import mytxs.models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0008_remove_medlem_navn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tilgang',
            options={'ordering': ['navn']},
        ),
        migrations.AddField(
            model_name='medlem',
            name='bilde',
            field=models.ImageField(null=True, upload_to=mytxs.models.Medlem.generateUploadTo),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='mellomnavn',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
