# Generated by Django 4.1.7 on 2023-04-25 12:26

from django.db import migrations, models
import mytxs.models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0009_alter_tilgang_options_medlem_bilde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medlem',
            name='bilde',
            field=models.ImageField(blank=True, null=True, upload_to=mytxs.models.Medlem.generateUploadTo),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='etternavn',
            field=models.CharField(default='Testbruker', max_length=50),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='fornavn',
            field=models.CharField(default='Autogenerert', max_length=50),
        ),
    ]
