# Generated by Django 4.2 on 2024-01-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0009_rename_korttittel_kor_navn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hendelse',
            name='beskrivelse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logg',
            name='strRep',
            field=models.CharField(max_length=255),
        ),
    ]
