# Generated by Django 4.2 on 2024-01-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0010_alter_hendelse_beskrivelse_alter_logg_strrep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hendelse',
            name='beskrivelse',
            field=models.TextField(blank=True),
        ),
    ]
