# Generated by Django 4.1.7 on 2023-04-27 12:13

from django.db import migrations
import mytxs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0011_alter_verv_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dekorasjoninnehavelse',
            name='start',
            field=mytxs.fields.MyDateField(),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='fødselsdato',
            field=mytxs.fields.MyDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vervinnehavelse',
            name='slutt',
            field=mytxs.fields.MyDateField(),
        ),
        migrations.AlterField(
            model_name='vervinnehavelse',
            name='start',
            field=mytxs.fields.MyDateField(),
        ),
    ]
