# Generated by Django 4.1.7 on 2023-05-01 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mytxs.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mytxs', '0012_alter_dekorasjoninnehavelse_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dekorasjoninnehavelse',
            name='dekorasjon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dekorasjonInnehavelse', to='mytxs.dekorasjon'),
        ),
        migrations.AlterField(
            model_name='dekorasjoninnehavelse',
            name='medlem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dekorasjonInnehavelse', to='mytxs.medlem'),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medlem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vervinnehavelse',
            name='medlem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vervInnehavelse', to='mytxs.medlem'),
        ),
        migrations.AlterField(
            model_name='vervinnehavelse',
            name='slutt',
            field=mytxs.fields.MyDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vervinnehavelse',
            name='verv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vervInnehavelse', to='mytxs.verv'),
        ),
    ]
