# Generated by Django 4.2 on 2024-06-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0013_alter_medlem_sjekkheftesynlig'),
    ]

    operations = [
        migrations.AddField(
            model_name='medlem',
            name='innlogginger',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
