# Generated by Django 4.2 on 2024-09-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0013_alter_medlem_sjekkheftesynlig'),
    ]

    operations = [
        migrations.AddField(
            model_name='medlem',
            name='emnekoder',
            field=models.CharField(blank=True),
        ),
    ]
