# Generated by Django 4.2 on 2024-07-12 10:50

from django.db import migrations, models
import django.db.models.deletion
import mytxs.fields
import mytxs.models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0013_alter_medlem_sjekkheftesynlig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertoar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbCacheField', models.JSONField(default=dict, editable=False)),
                ('navn', models.CharField(max_length=100)),
                ('dato', mytxs.fields.MyDateField(blank=True, null=True)),
                ('kor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repertoar', to='mytxs.kor')),
            ],
            options={
                'verbose_name_plural': 'repertoar',
                'ordering': ['kor', '-dato', 'navn', '-pk'],
                'unique_together': {('kor', 'navn')},
            },
        ),
        migrations.CreateModel(
            name='Sang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbCacheField', models.JSONField(default=dict, editable=False)),
                ('navn', models.CharField(max_length=100)),
                ('kor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanger', to='mytxs.kor')),
                ('repertoar', mytxs.fields.MyManyToManyField(blank=True, related_name='sanger', to='mytxs.repertoar')),
            ],
            options={
                'verbose_name_plural': 'sanger',
                'ordering': ['kor', 'navn', '-pk'],
                'unique_together': {('kor', 'navn')},
            },
        ),
        migrations.CreateModel(
            name='SangFil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbCacheField', models.JSONField(default=dict, editable=False)),
                ('navn', models.CharField(max_length=100)),
                ('stemmegruppe', models.CharField(blank=True, choices=[('S', 'S'), ('1S', '1S'), ('11S', '11S'), ('21S', '21S'), ('2S', '2S'), ('12S', '12S'), ('22S', '22S'), ('A', 'A'), ('1A', '1A'), ('11A', '11A'), ('21A', '21A'), ('2A', '2A'), ('12A', '12A'), ('22A', '22A'), ('T', 'T'), ('1T', '1T'), ('11T', '11T'), ('21T', '21T'), ('2T', '2T'), ('12T', '12T'), ('22T', '22T'), ('B', 'B'), ('1B', '1B'), ('11B', '11B'), ('21B', '21B'), ('2B', '2B'), ('12B', '12B'), ('22B', '22B')], max_length=3)),
                ('fil', models.FileField(upload_to=mytxs.models.SangFil.filUploadTo)),
                ('sang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filer', to='mytxs.sang')),
            ],
            options={
                'verbose_name_plural': 'sangfiler',
                'ordering': ['sang', 'navn', '-pk'],
                'unique_together': {('sang', 'navn')},
            },
        ),
    ]
