# Generated by Django 4.2 on 2024-06-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0014_dekorasjon_underordnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='dekorasjon',
            name='ikon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
