# Generated by Django 4.2 on 2024-07-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0014_repertoar_sang_sangfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sang',
            name='navn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
