# Generated by Django 4.2 on 2024-10-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0014_medlem_emnekoder'),
        ('mytxs', '0015_alter_medlem_innlogginger'),
    ]

    operations = [
    ]
