# Generated by Django 4.2 on 2024-07-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0015_alter_sang_navn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sang',
            name='navn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sangfil',
            name='navn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
