# Generated by Django 4.2 on 2024-12-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0016_merge_20241025_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verv',
            options={'ordering': ['kor', models.Case(models.When(navn='1S', then=0), models.When(navn='11S', then=1), models.When(navn='21S', then=2), models.When(navn='2S', then=3), models.When(navn='12S', then=4), models.When(navn='22S', then=5), models.When(navn='1A', then=6), models.When(navn='11A', then=7), models.When(navn='21A', then=8), models.When(navn='2A', then=9), models.When(navn='12A', then=10), models.When(navn='22A', then=11), models.When(navn='1T', then=12), models.When(navn='11T', then=13), models.When(navn='21T', then=14), models.When(navn='2T', then=15), models.When(navn='12T', then=16), models.When(navn='22T', then=17), models.When(navn='1B', then=18), models.When(navn='11B', then=19), models.When(navn='21B', then=20), models.When(navn='2B', then=21), models.When(navn='12B', then=22), models.When(navn='22B', then=23), default=24), 'navn'], 'verbose_name_plural': 'verv'},
        ),
        migrations.AlterUniqueTogether(
            name='lenke',
            unique_together={('kor', 'navn')},
        ),
    ]
