# Generated by Django 4.2 on 2024-08-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0016_remove_dekorasjon_underordnet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dekorasjon',
            name='erUnderordnet',
        ),
        migrations.AddField(
            model_name='dekorasjon',
            name='overvalør',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undervalør', to='mytxs.dekorasjon'),
        ),
    ]
