# Generated by Django 4.2 on 2024-07-14 17:38

from django.db import migrations, models
import django.db.models.functions.comparison
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0016_alter_sang_navn_alter_sangfil_navn'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sangfil',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sangfil',
            constraint=models.UniqueConstraint(models.F('sang'), models.F('stemmegruppe'), models.F('navn'), django.db.models.functions.text.Substr(models.F('fil'), django.db.models.functions.comparison.Greatest(django.db.models.functions.text.StrIndex(models.F('fil'), models.Value('.')), 1)), name='uniqueSongStemmegruppeExtentionWithName'),
        ),
    ]
