# Generated by Django 4.2 on 2024-07-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0017_alter_sangfil_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sangfil',
            name='uniqueSongStemmegruppeExtentionWithName',
        ),
        migrations.AddConstraint(
            model_name='sangfil',
            constraint=models.UniqueConstraint(models.F('sang'), models.F('stemmegruppe'), models.F('navn'), name='uniqueSongStemmegruppeExtentionWithName'),
        ),
    ]
