# Generated by Django 4.2 on 2024-09-22 19:52

from django.db import migrations, models
import mytxs.models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0017_remove_dekorasjon_erunderordnet_dekorasjon_overvalør'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dekorasjon',
            name='ikon',
            field=models.ImageField(blank=True, null=True, upload_to=mytxs.models.Dekorasjon.generateUploadTo),
        ),
    ]
