# Generated by Django 4.2 on 2025-01-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0017_alter_verv_options_alter_lenke_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medlem',
            name='ønskerVårbrev',
            field=models.BooleanField(blank=True, choices=[(True, 'Ønsker fysisk vårbrev'), (None, 'Ønsker digitalt vårbrev'), (False, 'Ønsker ikke vårbrev')], default=False, null=True, verbose_name='Ønsker vårbrev'),
        ),
    ]
