# Generated by Django 4.2 on 2025-01-21 19:42

from django.db import migrations, models
import django.db.models.deletion
import mytxs.models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0018_alter_medlem_ønskervårbrev'),
    ]

    operations = [
        migrations.AddField(
            model_name='dekorasjon',
            name='ikon',
            field=models.ImageField(blank=True, null=True, upload_to=mytxs.models.Dekorasjon.generateUploadTo),
        ),
        migrations.AddField(
            model_name='dekorasjon',
            name='overvalør',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undervalør', to='mytxs.dekorasjon'),
        ),
    ]
