# Generated by Django 4.2 on 2024-07-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0018_remove_sangfil_uniquesongstemmegruppeextentionwithname_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sangfil',
            name='uniqueSongStemmegruppeExtentionWithName',
        ),
        migrations.AlterUniqueTogether(
            name='sangfil',
            unique_together={('sang', 'navn', 'stemmegruppe')},
        ),
    ]
