# Generated by Django 4.2 on 2024-07-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0019_remove_sangfil_uniquesongstemmegruppeextentionwithname_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sangfil',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sangfil',
            constraint=models.UniqueConstraint(models.F('sang'), models.F('stemmegruppe'), models.F('navn'), name='uniqueSongStemmegruppeExtentionName'),
        ),
    ]
