# Generated by Django 4.2 on 2025-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0019_dekorasjon_ikon_dekorasjon_overvalør'),
    ]

    operations = [
        migrations.AddField(
            model_name='dekorasjon',
            name='bruktIKode',
            field=models.BooleanField(default=False, editable=False, help_text='<span title="Hvorvidt dekorasjonen er brukt i kode og følgelig ikke kan endres på av brukere.">(?)</span>', verbose_name='Brukt i kode'),
        ),
        migrations.AddField(
            model_name='dekorasjoninnehavelse',
            name='vrangstrupeDeviice',
            field=models.TextField(blank=True, verbose_name='Deviice'),
        ),
        migrations.AddField(
            model_name='dekorasjoninnehavelse',
            name='vrangstrupeSpørsmål',
            field=models.CharField(blank=True, max_length=255, verbose_name='Spørsmål'),
        ),
        migrations.AddField(
            model_name='dekorasjoninnehavelse',
            name='vrangstrupeSvar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Svar'),
        ),
        migrations.AlterField(
            model_name='tilgang',
            name='bruktIKode',
            field=models.BooleanField(default=False, editable=False, help_text='<span title="Hvorvidt tilgangen er brukt i kode og følgelig ikke kan endres på av brukere.">(?)</span>', verbose_name='Brukt i kode'),
        ),
        migrations.AlterField(
            model_name='verv',
            name='bruktIKode',
            field=models.BooleanField(default=False, editable=False, help_text='<span title="Hvorvidt vervet er brukt i kode og følgelig ikke kan endres på av brukere.">(?)</span>', verbose_name='Brukt i kode'),
        ),
    ]
