# Generated by Django 5.2.11 on 2026-02-19 18:28

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import mytxs.fields
import mytxs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0020_dekorasjon_bruktikode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertoar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbCacheField', models.JSONField(default=dict, editable=False)),
                ('navn', models.CharField(max_length=100)),
                ('dato', mytxs.fields.MyDateField(blank=True, null=True)),
                ('synlig', models.BooleanField(default=False, help_text='<span title="Om dette repertoaret alltid skal være synlig øverst i notearkivet.">(?)</span>')),
                ('kor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repertoar', to='mytxs.kor')),
            ],
            options={
                'verbose_name_plural': 'repertoar',
                'ordering': ['kor', '-dato', 'navn', '-pk'],
                'unique_together': {('kor', 'navn')},
            },
        ),
        migrations.CreateModel(
            name='Sang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbCacheField', models.JSONField(default=dict, editable=False)),
                ('navn', models.CharField(max_length=100)),
                ('kortype', models.CharField(blank=True, choices=[('Mannskor', 'Mannskor'), ('Damekor', 'Damekor'), ('Blandakor', 'Blandakor'), ('Begge', 'Begge'), ('', '')])),
                ('notis', models.TextField(blank=True)),
                ('kor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanger', to='mytxs.kor')),
                ('repertoar', mytxs.fields.MyManyToManyField(blank=True, related_name='sanger', to='mytxs.repertoar')),
            ],
            options={
                'verbose_name_plural': 'sanger',
                'ordering': ['kor', 'navn', '-pk'],
                'unique_together': {('kor', 'navn')},
            },
        ),
        migrations.CreateModel(
            name='SangFil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbCacheField', models.JSONField(default=dict, editable=False)),
                ('navn', models.CharField(blank=True, max_length=100)),
                ('stemmegruppe', models.CharField(blank=True, choices=[('S', 'S'), ('1S', '1S'), ('11S', '11S'), ('21S', '21S'), ('2S', '2S'), ('12S', '12S'), ('22S', '22S'), ('A', 'A'), ('1A', '1A'), ('11A', '11A'), ('21A', '21A'), ('2A', '2A'), ('12A', '12A'), ('22A', '22A'), ('T', 'T'), ('1T', '1T'), ('11T', '11T'), ('21T', '21T'), ('2T', '2T'), ('12T', '12T'), ('22T', '22T'), ('B', 'B'), ('1B', '1B'), ('11B', '11B'), ('21B', '21B'), ('2B', '2B'), ('12B', '12B'), ('22B', '22B')], max_length=3)),
                ('skjul', models.BooleanField(default=False)),
                ('fil', models.FileField(upload_to=mytxs.models.SangFil.filUploadTo)),
                ('sang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filer', to='mytxs.sang')),
            ],
            options={
                'verbose_name_plural': 'sangfiler',
                'ordering': ['sang', models.Case(models.When(stemmegruppe='1S', then=0), models.When(stemmegruppe='11S', then=1), models.When(stemmegruppe='21S', then=2), models.When(stemmegruppe='2S', then=3), models.When(stemmegruppe='12S', then=4), models.When(stemmegruppe='22S', then=5), models.When(stemmegruppe='1A', then=6), models.When(stemmegruppe='11A', then=7), models.When(stemmegruppe='21A', then=8), models.When(stemmegruppe='2A', then=9), models.When(stemmegruppe='12A', then=10), models.When(stemmegruppe='22A', then=11), models.When(stemmegruppe='1T', then=12), models.When(stemmegruppe='11T', then=13), models.When(stemmegruppe='21T', then=14), models.When(stemmegruppe='2T', then=15), models.When(stemmegruppe='12T', then=16), models.When(stemmegruppe='22T', then=17), models.When(stemmegruppe='1B', then=18), models.When(stemmegruppe='11B', then=19), models.When(stemmegruppe='21B', then=20), models.When(stemmegruppe='2B', then=21), models.When(stemmegruppe='12B', then=22), models.When(stemmegruppe='22B', then=23), default=24), 'navn', '-pk'],
                'constraints': [models.UniqueConstraint(models.F('sang'), models.F('navn'), models.F('stemmegruppe'), django.db.models.functions.text.Lower(django.db.models.functions.text.Substr(models.F('fil'), django.db.models.expressions.CombinedExpression(django.db.models.functions.text.StrIndex(models.F('fil'), models.Value('.')), '+', models.Value(1)))), name='sangFil_unique_on_extention')],
            },
        ),
    ]
