# Generated by Django 4.2 on 2024-07-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0021_remove_sangfil_uniquesongstemmegruppeextentionname_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sangfil',
            name='uniqueSongStemmegruppeExtentionName',
        ),
        migrations.AddConstraint(
            model_name='sangfil',
            constraint=models.UniqueConstraint(models.F('sang'), models.F('navn'), models.F('stemmegruppe'), name='uniqueSongStemmegruppeExtentionName', violation_error_message='Må ha unik sang, navn, stemmegruppe og filtype'),
        ),
    ]
