# Generated by Django 5.2.11 on 2026-02-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0021_repertoar_sang_sangfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertoar',
            name='synlig',
            field=models.BooleanField(default=False, help_text='<span title="Om dette repertoaret alltid skal være synlig øverst i notearkivet.">(?)</span>'),
        ),
    ]
