# Generated by Django 5.2.11 on 2026-03-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0021_repertoar_sang_sangfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sang',
            name='kortype',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Mannskor', 'Mannskor'), ('Damekor', 'Damekor'), ('Blandakor', 'Blandakor'), ('Begge', 'Begge')]),
        ),
    ]
