# Generated by Django 4.2 on 2024-07-14 18:04

from django.db import migrations, models
import django.db.models.functions.comparison
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0022_remove_sangfil_uniquesongstemmegruppeextentionname_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sangfil',
            name='uniqueSongStemmegruppeExtentionName',
        ),
        migrations.AddConstraint(
            model_name='sangfil',
            constraint=models.UniqueConstraint(models.F('sang'), models.F('navn'), models.F('stemmegruppe'), django.db.models.functions.text.Substr(models.F('fil'), django.db.models.functions.comparison.Greatest(django.db.models.functions.text.StrIndex(models.F('fil'), models.Value('.')), 1)), name='uniqueSongStemmegruppeExtentionName', violation_error_message='Må ha unik sang, navn, stemmegruppe og filtype'),
        ),
    ]
