# Generated by Django 5.2.12 on 2026-05-02 12:46
# Manuelt redigert for å legg inn UnaccentExtension, så sangsøk ignorerer diakritiske tegn.

from django.contrib.postgres.operations import UnaccentExtension
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0022_alter_sang_kortype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sang',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sang',
            constraint=models.UniqueConstraint(models.F('kor'), django.db.models.functions.text.Lower('navn'), name='sang_unique_name'),
        ),
        UnaccentExtension(),
    ]
