# Generated by Django 4.2 on 2024-08-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0023_remove_sangfil_uniquesongstemmegruppeextentionname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sangfil',
            options={'ordering': ['sang', 'navn', models.Case(models.When(stemmegruppe='Dirigent', then=0), models.When(stemmegruppe='S', then=1), models.When(stemmegruppe='1S', then=2), models.When(stemmegruppe='11S', then=3), models.When(stemmegruppe='21S', then=4), models.When(stemmegruppe='2S', then=5), models.When(stemmegruppe='12S', then=6), models.When(stemmegruppe='22S', then=7), models.When(stemmegruppe='A', then=8), models.When(stemmegruppe='1A', then=9), models.When(stemmegruppe='11A', then=10), models.When(stemmegruppe='21A', then=11), models.When(stemmegruppe='2A', then=12), models.When(stemmegruppe='12A', then=13), models.When(stemmegruppe='22A', then=14), models.When(stemmegruppe='T', then=15), models.When(stemmegruppe='1T', then=16), models.When(stemmegruppe='11T', then=17), models.When(stemmegruppe='21T', then=18), models.When(stemmegruppe='2T', then=19), models.When(stemmegruppe='12T', then=20), models.When(stemmegruppe='22T', then=21), models.When(stemmegruppe='B', then=22), models.When(stemmegruppe='1B', then=23), models.When(stemmegruppe='11B', then=24), models.When(stemmegruppe='21B', then=25), models.When(stemmegruppe='2B', then=26), models.When(stemmegruppe='12B', then=27), models.When(stemmegruppe='22B', then=28), models.When(stemmegruppe='ukjentStemmegruppe', then=29), default=30), '-pk'], 'verbose_name_plural': 'sangfiler'},
        ),
        migrations.AlterModelOptions(
            name='verv',
            options={'ordering': ['kor', models.Case(models.When(navn='Dirigent', then=0), models.When(navn='S', then=1), models.When(navn='1S', then=2), models.When(navn='11S', then=3), models.When(navn='21S', then=4), models.When(navn='2S', then=5), models.When(navn='12S', then=6), models.When(navn='22S', then=7), models.When(navn='A', then=8), models.When(navn='1A', then=9), models.When(navn='11A', then=10), models.When(navn='21A', then=11), models.When(navn='2A', then=12), models.When(navn='12A', then=13), models.When(navn='22A', then=14), models.When(navn='T', then=15), models.When(navn='1T', then=16), models.When(navn='11T', then=17), models.When(navn='21T', then=18), models.When(navn='2T', then=19), models.When(navn='12T', then=20), models.When(navn='22T', then=21), models.When(navn='B', then=22), models.When(navn='1B', then=23), models.When(navn='11B', then=24), models.When(navn='21B', then=25), models.When(navn='2B', then=26), models.When(navn='12B', then=27), models.When(navn='22B', then=28), models.When(navn='ukjentStemmegruppe', then=29), default=30), 'navn'], 'verbose_name_plural': 'verv'},
        ),
        migrations.RemoveConstraint(
            model_name='sangfil',
            name='uniqueSongStemmegruppeExtentionName',
        ),
        migrations.AddField(
            model_name='sang',
            name='notis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='sangfil',
            unique_together={('sang', 'navn', 'stemmegruppe')},
        ),
    ]
