# Generated by Django 4.2 on 2024-08-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0024_alter_sangfil_options_alter_verv_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sangfil',
            name='skjul',
            field=models.BooleanField(default=False),
        ),
    ]
