# Generated by Django 4.2 on 2024-08-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytxs', '0025_sangfil_skjul'),
    ]

    operations = [
        migrations.AddField(
            model_name='sang',
            name='kortype',
            field=models.CharField(blank=True, choices=[('mannskor', 'mannskor'), ('damekor', 'damekor'), ('blandakor', 'blandakor'), ('begge', 'begge'), ('', '')]),
        ),
    ]
